### PR TITLE
fix: Fix deprecation notice in `trim_words` method when `null` is passed.

### LINKED ISSUE #3129: [BUG] prevent deprecation notice from truncate filter
### Expected Behavior

No deprecation notice.

### Actual behavior

Running into this deprecation notice:

`strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated | wp-content/themes/theme-name/vendor/timber/timber/src/TextHelper.php:68`

### Steps to reproduce behavior

Pass the truncate filter past a null valued variable.  Quick and easy test: `{{ null|truncate(25) }}`

### Notes

Just avoid passing in a null value into `strip_tags()` in `TextHelper.php` line ~68.  Maybe just return a blank string at the beginning of the `trim_words()` method if `empty($text)`.

### What version of Timber are you using?

Timber 2.3.2

### What version of WordPress are you using?

Wordpress 6.8.2

### What version of PHP are you using?

8.2.29

### How did you install Timber?

Installed or updated Timber through Composer

### PR DESCRIPTION
**Pull request by Levdbas**
Related:

- #3129

## Issue
As said in #3129 , passing null to `TextHelper::trip_words ` or `truncate`, causes a deprecation message.

## Solution
Short-circuit the method early when text is null.

## Testing
yes

### CODE REVIEW

File: src/TextHelper.php [hunk 1]
```diff
@@ -43,6 +43,10 @@ public static function trim_characters($text, $num_chars = 60, $more = '&hellip;
      */
     public static function trim_words($text, $num_words = 55, $more = null, $allowed_tags = 'p a span b i br blockquote')
     {
+        if (null === $text) {
```
Comment (gchtr) [inline src/TextHelper.php]: We could also return here when the text is empty, right?

Comment (Levdbas) [reply src/TextHelper.php]: as in 

`if(empty($text)) {`

@gchtr ? That would short circuit the function a lot earlier in some cases. Which sounds like a good idea.

Comment (gchtr) [reply src/TextHelper.php]: Yeah, exactly like that.

My only question is: does this change the logic so that `$more` will not be displayed, when it was before, even with empty text? And is this an acceptable change? In my opinion, this would be okay.

In the future, this function will probably get proper parameter types as well (`trim_words(?string $text, ...)`, so a check for `empty()` would catch empty text and null values, while other values would be discarded earlier with an error.

**Review by gchtr — APPROVED** [review]

**Comment by gchtr** [comment]
It’s weird. The PHP coding standards action has an error, but when I run it locally with PHP 8.1, I see no errors to fix. The action seems to be using PHP 8.1 as well, so I can’t say what’s wrong.

But I think this doesn’t block us from merging this PR.
