### PR TITLE
2873 bug cannot use timberpostfactory when extending post class as the method is private

### LINKED ISSUE #2873: [BUG] Cannot use Timber\Post::factory when extending Post class as the method is private
### Expected Behavior

When extending a Timber\Post, I should be able to access the factory() method. 

I'm trying to override the children() method which needs to have access to the factory.

### Actual behavior

Timber\Post::factory() is private and cannot be accessed by inhertitance.

### Steps to reproduce behavior

1. Create a class that extends Timber\Post
2. Try to access the factory method
3. It returns false instead of a PostFactory object.

### Notes

_No response_

### What version of Timber are you using?

Timber 2.0

### What version of WordPress are you using?

WordPress 6.4.2

### What version of PHP are you using?

PHP 8.1

### How did you install Timber?

Installed or updated Timber through Composer

### PR DESCRIPTION
**Pull request by Levdbas**
Related:

- #2873

## Issue
The Timber\Post::factory() is private and thus cannot be overwritten. So there was no way to alter the query to get the children.

## Solution
Added two new ways to alter the query:

1. added a filter to change the arguments
2. Add a new functionality to overload the children() parameter with query arguments.

I came up with the second approach later because that might be easier for most people. You could just change the arguments in your `children` call or make a separate children method in your custom class that calls the parent::children method with these additional arguments.

## Impact
No negative impact since loading the argument with a string or a non-indexed array still works.

## Usage Changes
No

## Considerations
Maybe one of these methods is enough. Not sure if adding the full argument list is a bit too much for this method. 

## Testing
Yes! First unit test I've ever written 👯

### CODE REVIEW

File: src/Post.php [hunk 1]
```diff
@@ -994,23 +994,68 @@ public function category()
...
     {
+        $post_type = 'any';
+        if (\is_string($args)) {
+            $post_type = $args;
+        } elseif (\array_values($args) === $args) {
+            $post_type = $args;
+        } elseif (\is_array($args)) {
+            $additional_args = $args;
+        }
+
```
Comment (gchtr) [inline src/Post.php]: Could we maybe rewrite this using `wp_parse_args()`?

```suggestion
		if (\is_string($args) || \array_values($args) === $args) {
			$args = [
				'post_type' => $args,
			];
		}

		$args = wp_parse_args($args, [
            'post_parent' => $this->ID,
            'post_type' => 'any',
            'posts_per_page' => -1,
            'orderby' => 'menu_order title',
            'order' => 'ASC',
            'post_status' => 'publish',
        ]);
```

Then, we wouldn’t need `$additional_args`.

File: src/Post.php [hunk 2]
```diff
@@ -994,23 +994,68 @@ public function category()
...
-        $query = 'post_parent=' . $this->ID . '&post_type[]=' . $post_type . '&posts_per_page=-1&orderby=menu_order title&order=ASC&post_status[]=publish';
+
+        $args = [
+            'post_parent' => $this->ID,
+            'post_type' => $post_type,
+            'posts_per_page' => -1,
+            'orderby' => 'menu_order title',
+            'order' => 'ASC',
+            'post_status' => 'publish',
+        ];
```
Comment (gchtr) [inline src/Post.php]:
```suggestion

```

File: src/Post.php [hunk 3]
```diff
@@ -994,23 +994,68 @@ public function category()
...
+
         if ($this->post_status === 'publish') {
-            $query .= '&post_status[]=inherit';
+            $args['post_status'] = ['publish', 'inherit'];
+        }
+
+        if (isset($additional_args)) {
+            $args = \array_merge($args, $additional_args);
         }
```
Comment (gchtr) [inline src/Post.php]:
```suggestion

```

**Review by gchtr — CHANGES_REQUESTED** [review]
Nice one, @Levdbas! Thanks for this.

I only have a suggestion about the args handling.

File: src/Post.php (hunk 1 above)
Comment (Levdbas) [reply src/Post.php]: Fixed this with some extra sauce to also get the parent status working

**Comment by Levdbas** [comment]
@gchtr , this is now fixed!

File: src/Post.php [hunk 4]
```diff
@@ -994,23 +994,54 @@ public function category()
...
+        /**
+         * Filters the arguments for the query used to get the children of a post.
+         *
+         * This filter is used by the `Timber\Post::children()` method. It allows you to modify the
+         * arguments for the `get_children` function. This way you can change the query to get the
+         * children of a post.
+         *
+         * @example
+         * ```
+         * add_filter( 'timber/post/children_args', function( $args, $post ) {
```
Comment (gchtr) [inline src/Post.php:1026]:
```suggestion
         * add_filter( 'timber/post/children/query_args', function( $args, $post ) {
```

File: src/Post.php [hunk 5]
```diff
@@ -994,23 +994,54 @@ public function category()
...
+         * } );
+         * ```
+         *
+         * @see   \Timber\Post::children()
+         * @since 2.1.0
+         *
+         * @param array        $arguments An array of arguments for the `get_children` function.
+         * @param Post $post   The post object.
+         */
+        $args = \apply_filters('timber/post/children_args', $args, $this);
```
Comment (gchtr) [inline src/Post.php:1042]:
```suggestion
        $args = \apply_filters('timber/post/children/query_args', $args, $this);
```

**Review by gchtr — APPROVED** [review]
Hey @Levdbas, thanks for the updates!

I have only one small change that I didn’t check before. I would rename the filter name to `timber/post/children/query_args`. This way, it’s more clear what args are being filtered.

**Comment by Levdbas** [comment]
@gchtr , applied and merged :)

**Comment by gchtr** [comment]
@Levdbas Great, thanks! 🎉
